import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.scss';
import NavBar from '@/components/NavBar/NavBar';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600'], 
});

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={poppins.className}>
        <div className='wrapper'>
        <NavBar />
        <main className='container'>{children}</main>  
        </div>
      </body>
    </html>
  );
}
